EShop.MVC2/Controllers/AdminController.cs
using EShop.Entity;
using EShop.ServiceLayer;
using ImageResizer;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;

namespace EShop.MVC2.Controllers
{
    public class AdminController : Controller
    {
        private IDataService dataService;

        public AdminController(IDataService service)
        {
            dataService = service;
        }

        //Метод для обработки нажатия на кнопку "Изменить изображение" на странице описания модели
        //Из него идет перенаправление во View/Upload, где будет форма для выбора новой картинки 
        [Authorize(Roles = "Admins")]
        public ActionResult Upload(int? id, int? id2, int? id3)
        {
            ViewBag.FileId = (int)id;
            ViewBag.ModelId = (int)id2;
            //а вот тут костыль. Если не не запихнуть в ViewBag.Selected категорию товара, то панель навигации крашится.
            //хотя во View Model, откуда мы сюда приходим, в этом ViewBag.Selected еще значение есть.
            //а во View Upload, куда мы отсюда пойдем, его уже нету...  
            ViewBag.Selected = (int)id3;//
            return View("Upload");
        }

        [Authorize(Roles = "Admins")]
        public ActionResult CnahgeCategory(int? id, int? id2, int? id3)
        {
            ViewBag.FileId = (int)id;
            ViewBag.ModelId = (int)id2;

            ViewBag.Selected = (int)id3;
            return Redirect("~/Home/Model/" + (int)id);
        }

        //Метод для изменения текущих файлов изображения товара (и ico, и jpeg)
        //Из него идет возврат во View/Model.cshtml, где должна отобразиться новая картинка
        //Используется библиотека ImageResizer из NuGet 
        [Authorize(Roles = "Admins")]
        public ActionResult UploadFile()
        {
            HttpPostedFileBase file = Request.Files["file"];
            var imageId = Request.Form["imageId"];
            var modelId = Request.Form["modelId"];
            var req = Request.Files.Count;
            if (file != null)
            {
                //Declare a new dictionary to store the parameters for the image versions.
                var versions = new Dictionary<string, string>();

                var path = Server.MapPath("~/Content/Images/");

                //Define the versions to generate
                versions.Add("ico_", "maxwidth=100&format=jpg");
                versions.Add("img_", "maxwidth=400&format=jpg");

                //Generate each version
                foreach (var suffix in versions.Keys)
                {
                    file.InputStream.Seek(0, SeekOrigin.Begin);

                    //Let the image builder add the correct extension based on the output file type
                    ImageBuilder.Current.Build(
                        new ImageJob(
                            file.InputStream,
                            path + suffix + imageId,
                            new Instructions(versions[suffix]),
                            false,
                            true));
                }
            }
            return Redirect("~/Home/Model/"+ modelId);
        }

        //Метод для обработки клика по меню "Добавить товар" в панели админа
        //Сюда попадаем из частичного представления AdminPanel.cshtml (см.  @Html.ActionLink("Добавить товар", "AddGoods", "Admin"...)
        //Задача метода положить во ViewBag данные для выпадающих меню о доступности и способе доставки товара 
        //и передать во View AddGoods.cshtml пустую модель, или неполную для исправления выявленных ошибок
        [Authorize(Roles = "Admins")]
        public ActionResult AddGoods(Model model)
        {
            ViewBag.AvailabilityListModel = new SelectList(GetAvalabilityList(), "Id", "AvailabilityType");
            ViewBag.DeliveryListModel = new SelectList(GetDeliveryList(), "Id", "DeliveryType");
            return View("AddGoods", model);
        }

        //Метод для добавления в БД нового товара
        //Сюда попадаем из ~View/Home/AddGoods.cshtml
        //model должна получить данные из формы в той вьюхе        
        [HttpPost]
        [Authorize(Roles = "Admins")]
        public ActionResult AddModel(Model model)
        {
            List<string> error = new List<string>();
            if (Request.Form["newCategoryId"] != null)
                model.CategoryId = Int16.Parse(Request.Form["newCategoryId"]);
            else
                error.Add("Укажите категорию");
            if (Request.Form["Price"] != null)
            {
                try
                {
                    model.Price = Decimal.Parse(Request.Form["Price"].ToString().Replace(".", ","));// замена . на , на случай неправильного ввода цены
                }
                catch
                {
                    error.Add("Ошибка ввода цены");
                }               
            }                
            else
                error.Add("Введите цену");
            if (model.Title == null)
                error.Add("Введите краткое описание товара");
            if (model.Description == null)
                error.Add("Введите подробное описание товара");
            if(model.Warranty == 0)
                error.Add("Введите срок гарантии");
            if (error.Count > 0)
            {
                ViewBag.Error = error;
                ViewBag.AvailabilityListModel = new SelectList(GetAvalabilityList(), "Id", "AvailabilityType");
                ViewBag.DeliveryListModel = new SelectList(GetDeliveryList(), "Id", "DeliveryType");
                return View("AddGoods", model);
            }
                
            model.ImageId = dataService.GetMaxImageId() + 1;// присваиваем для ImageId значение, следующее после максимального, содержащегося в таблице Models базы
            var id = dataService.AddModel(model);
            return Redirect("~/Home/Model/" + model.Id); //переход на страницу редактирования добавленного товара
        }

        //Meтод для возврата списка всех возможных значений поля AvailabilityType найденных в БД [Availability]
        //Все как в контроллере Search, только тут без значений по дефолту
        //используется кэш
        List<Availability> GetAvalabilityList()
        {
            IEnumerable<Availability> avail;
            List<Availability> availabilityList = new List<Availability>();
            var cacheAvailabilityList = HttpContext.Cache;
            if (cacheAvailabilityList["availabilityListModel"] == null)
            {
                avail = dataService.GetAvailabilityTypes();
                foreach (var item in avail)
                {
                    availabilityList.Add(new Availability { Id = item.Id, AvailabilityType = item.AvailabilityType });
                    cacheAvailabilityList.Insert("availabilityListModel", availabilityList, null, Cache.NoAbsoluteExpiration, TimeSpan.FromHours(1));
                }
            }
            availabilityList = cacheAvailabilityList["availabilityListModel"] as List<Availability>;
            return availabilityList;
        }

        //Meтод для возврата списка всех возможных значений поля DeliveryType найденных в БД [Delivery]
        //Все как в контроллере Search, только тут без значений по дефолту
        //используется кэш
        List<Delivery> GetDeliveryList()
        {
            IEnumerable<Delivery> delivery;
            List<Delivery> deliveryList = new List<Delivery>();
            var cacheDeliveryList = HttpContext.Cache;
            if (cacheDeliveryList["deliveryListModel"] == null)
            {
                delivery = dataService.GetDeliveryTypes();
                foreach (var item in delivery)
                {
                    deliveryList.Add(new Delivery { Id = item.Id, DeliveryType = item.DeliveryType });
                    cacheDeliveryList.Insert("deliveryListModel", deliveryList, null, Cache.NoAbsoluteExpiration, TimeSpan.FromHours(1));
                }
            }
            deliveryList = cacheDeliveryList["deliveryListModel"] as List<Delivery>;
            return deliveryList;
        }
    }
}

EShop.MVC2/Controllers/SearchController.cs
using EShop.Entity;
using EShop.MVC2.Models;
using EShop.ServiceLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Caching;
using System.Web.Mvc;

namespace EShop.MVC2.Controllers
{
    public class SearchController : Controller
    {
        private IDataService dataService;

        public SearchController (IDataService service)
        {
            dataService = service;
        }

        //Метод для сбора данных для выпадающих меню в форме поиска:
        // - список категорий товаров
        // - варианты наличия товара
        //Запрос сюда приходит из мастер-страницы /Views/Shared/_Layout.cshtml
        //(см.@{ Html.RenderAction("Index", "Search"); })
        //полученные данные отправляются в частичное представление /Views/Search/Searching.cshtml для отрисовки HTML разметки
        public ActionResult Index()
        {
            //для начала достанем все корневые категории, как и для левой панели с навигацией
            IEnumerable<Category> root = null;
            var cacheRoot = HttpContext.Cache;
            if (cacheRoot["root"] == null)
            {
                root = dataService.RootCategories;
                cacheRoot.Insert("root", root, null, Cache.NoAbsoluteExpiration, TimeSpan.FromHours(1));
            }
            root = cacheRoot["root"] as IEnumerable<Category>;
            //далее берем из кэша или генерим список только из Category.Name и Category.Id
            //он нужен, чтоб не передавать лишнюю инфу в DropDownList через ViewBag
            //сразу закладываем первый элемент для возможности поиска по всем категориям по умолчанию
            List<CategoryList> categoryList = new List<CategoryList>();
            var cacheCategoryList = HttpContext.Cache;
            if (cacheCategoryList["categoryList"] == null)
            {
                categoryList.Add(new CategoryList { Id = 0, Name = "Все категории" });
                foreach (var item in root)
                    categoryList.Add( new CategoryList { Id = item.Id, Name = item.Name });

                cacheCategoryList.Insert("categoryList", categoryList, null, Cache.NoAbsoluteExpiration, TimeSpan.FromHours(1));
            }
            categoryList = cacheCategoryList["categoryList"] as List<CategoryList>;

            SelectList categories = new SelectList(categoryList, "Id", "Name", "0");
            ViewBag.CategoriesList = categories;

            //аналогично берем из кэша или генерим список <Availability> AvailabilityType и Id
            var availabilityList = GetAvalabilityList();
            SelectList availability = new SelectList(availabilityList, "Id", "AvailabilityType", "0");
            ViewBag.AvailabilityList = availability;

            return PartialView("Searching");
        }
        
        //[HttpGet]
        public ActionResult SearchRequest()
        {
            List<SearchResult> resultList = new List<SearchResult>();//список с результаиами совпадений запроса с Model.Description
            //тут начинается разбор запроса поиска
            string searchQuery = Request.QueryString["search_query"];
            if (searchQuery != "")
            {
                byte availability = Byte.TryParse(Request.QueryString["availability"], out availability) ? availability : (byte)0;//если в поле "availability" пришла какая-то ерунда, то заносим туда 0 
                var priceFrom = TryParseNullable(Request.QueryString["from"]);
                var priceTo = TryParseNullable(Request.QueryString["to"]);
                //var searchWords = searchQuery.Split(' ').Where(x => !string.IsNullOrWhiteSpace(x)).ToArray();//делим поисковый запрос на отдельные слова
                //ViewBag.SearchWords = searchWords; //и отправлем этот массив для SerachResult.cshtml
                ViewBag.SearchQuery = searchQuery;
                int category = Int32.TryParse(Request.QueryString["category"], out category) ? category : 0;//если вдруг в поле "category" пришла какая-то ерунда, то заносим туда 0
                if (category == 0)//Если категория не указана, то придется искать ВСЕ товары
                {
                    IEnumerable<Category> root = null;
                    var cacheRoot = HttpContext.Cache;
                    if (cacheRoot["root"] == null)
                    {
                        root = dataService.RootCategories;
                        cacheRoot.Insert("root", root, null, Cache.NoAbsoluteExpiration, TimeSpan.FromHours(1));
                    }
                    root = cacheRoot["root"] as IEnumerable<Category>;
                    foreach (var item in root)
                        //AddRange тут потому что складываются списки
                        resultList.AddRange(GetSearchResultList(availability, priceFrom, priceTo, searchQuery, item.Id));
                }
                else//тут поиск по отдельной выбранной категории
                    resultList.AddRange(GetSearchResultList(availability, priceFrom, priceTo, searchQuery, category));        
                //foreach (var word in searchWords)
                //{

                //}
            }
            //Далее создаем новый список из неповторяющихся элементов списка resultList
            //почему-то метод Distinct() не работал, пришлось делать ручками
            List<SearchResult> finalList = new List<SearchResult>();
            List<int> resultListId = new List<int>();
            foreach (var item in resultList)
            {                
                if (!resultListId.Contains(item.Id))
                {
                    finalList.Add(item);
                    resultListId.Add(item.Id);
                }
            }
            //сортировка списка по количеству найденных совпадений
            //пришлось сделать еще один список :(
            //var fnlList = finalList.OrderBy(x => x.Id);
            return PartialView("SearchResult", finalList);
        }

        //Метод для создания списка результата поиска
        List<SearchResult> GetSearchResultList(int availability, decimal? priceFrom, decimal? priceTo, string word, int categoryId)
        {
            List<SearchResult> resultList = new List<SearchResult>();
            var avalabilityList = GetAvalabilityList();
            var models = dataService.GetModels(categoryId);
            foreach (var m in models)
            {
                if (availability == 0 || availability == m.AvailabilityId)//если критерий наличия подходит, то разбираем запрос дальше 
                {
                    if ((priceFrom == null || priceFrom <= m.Price) && (priceTo == null || priceTo >= m.Price))//если критерий цены подходит, то наконец сравниваем строки
                    {
                        if (m.Description.Contains(word))
                            resultList.Add(new SearchResult
                                    {
                                        Description = m.Description,
                                        Id = m.Id,
                                        ImageId = m.ImageId,
                                        Price = m.Price
                                    });
                    }
                }
            }
            return resultList;
        }
        //Метод для проверки наличия в описании товара слова из поискового запроса
        bool  FindString (string searchQuery, string description)
        {
            bool result = false;
            var words = description.Split(' ').ToArray();
            if (words.Where(x => x.Contains(searchQuery)).Count() > 0)//есть ли совпадение (полное или частичное) searchQuery в массиве words
                result = true;
            return result;
        }

        //Meтод для возврата списка всех возможных значений поля AvailabilityType найденных в БД [Availability]
        //В спиок заносится первый элемент  Id = 0, AvailabilityType = "Любое", которого нет в БД, но он нужен для дефолтного элемента в выпадающем списке 
        //используется кэш
        List<Availability> GetAvalabilityList()
        {
            IEnumerable<Availability> avail;
            List<Availability> availabilityList = new List<Availability>();
            var cacheAvailabilityList = HttpContext.Cache;
            if (cacheAvailabilityList["availabilityList"] == null)
            {
                avail = dataService.GetAvailabilityTypes();
                availabilityList.Add(new Availability { Id = 0, AvailabilityType = "Любое" });
                foreach (var item in avail)
                {
                    availabilityList.Add(new Availability { Id = item.Id, AvailabilityType = item.AvailabilityType });
                    cacheAvailabilityList.Insert("availabilityList", availabilityList, null, Cache.NoAbsoluteExpiration, TimeSpan.FromHours(1));
                }
            }
            availabilityList = cacheAvailabilityList["availabilityList"] as List<Availability>;
            return availabilityList;
        }

        //Метод парсинга строки в число
        //Выдает nullable тип - это нужно если в поле цены пользователь введет какую-то фигню
        decimal? TryParseNullable(string val)
        {
            decimal outValue;
            return Decimal.TryParse(val, out outValue) ? (decimal?)outValue : null;
        }


    }
}

EShop.MVC2/Views/Shared/AddGoods.cshtml
@{
    ViewBag.Title = "Добавить товар";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model EShop.Entity.Model

@{var error = ViewBag.Error as List<string>;}
@{using (Html.BeginForm("AddModel", "Admin", new { enctype = "multipart/form-data" }, FormMethod.Post))
    {
        //Model.AvailabilityId = 1;
        //Model.DeliveryId = 1;
<table border="0" width="800" border-collapse collapse;" class="categories_list">
    <tr>
        <td colspan="2" style="padding:20px">
            <a>Внимание!<br />
            Сначала введите все данные о товаре<br />
            Затем загрузите изображение товара в меню редактирования товара, который будет сохранен в базе данных</a><br /><br />
        </td>
    </tr>
    <tr>
        <td colspan="2">Назначьте категорию товара:</td>
    </tr>
    <tr>
        <td colspan="2" style="text-align:center">@{Html.RenderAction("WholeTree", "Home");}</td>
    </tr>

    <tr>
        <td width="80">
            <a>Краткое описание:</a>
        </td>
        <td>
            <a>@Html.TextArea("Title", "", 2, 100, new { maxlength = "512", @class = "categories_list", width = "100%" })</a>
        </td>
    </tr>

    <tr>
        <td>
            <a>Описание:</a>
        </td>
        <td>
            <a>@Html.TextArea("Description", "", 2, 100, new { maxlength = "2048", @class = "categories_list", width = "100%" })</a>
        </td>
    </tr>
    <tr>
        <td>
            <a>Цена:</a>
        </td>
        <td>
            <a>@Html.TextArea("Price", "", 1, 10, new { maxlength = "10", @class = "categories_list", width = "100%" })</a>
        </td>
    </tr>
    <tr>
        <td>
            <a>Гарантия:</a>
        </td>
        <td>
            <a>@Html.TextArea("Warranty", "", 1, 2, new { maxlength = "2", @class = "categories_list", width = "100%" })</a>
        </td>
    </tr>
    <tr>
        <td>
            <a>Наличие:</a>
        </td>
        <td>
            <a>@Html.DropDownListFor(model => model.AvailabilityId, (IEnumerable<SelectListItem>)ViewBag.AvailabilityListModel, new { @class = "categories_list" })</a>
        </td>
    </tr>
    <tr>
        <td>
            <a>Доставка:</a>
        </td>
        <td>
            <a>@Html.DropDownListFor(model => model.DeliveryId, (IEnumerable<SelectListItem>)ViewBag.DeliveryListModel, new { @class = "categories_list" })</a>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="text-align:right; ">
            <input type="submit" value="Cохранить" />
        </td>
    </tr>
    @if(error != null && error.Count >0)
    {
        foreach(var item in error)
        {
            <tr>
                <td colspan="2" style="color:red">
                    @item
                </td>
            </tr>
        }
    }
</table>
}

}

EShop.MVC2/Views/Shared/AdminPanel.cshtml
@*Частичное представление для отрисовки меню админа.
Вызывается из Layout.cshtml (td id="rightPanel")
Оно будет отображаться если залогинен пользователь с ролью "Admins"*@
@{
    var identity = this.ViewContext.HttpContext.User.Identity;
}

<div style="overflow:hidden;" class="categories_list">
    @if (Request.IsAuthenticated && identity.IsAuthenticated && Roles.GetRolesForUser(identity.Name).Contains("Admins"))
    {
        <hr />
        <div style="background-color:lightcyan">
            
            <b>Меню администратора</b><br /><br />
            @Html.ActionLink("Пользователи", "Admin", "Account", new { controller = "Account" }, new { style = "text-decoration: none; color:black;" }) <br />
            @Html.ActionLink("Добавить товар", "AddGoods", "Admin", new { controller = "Home" }, new { style = "text-decoration: none; color:black;" }) <br />
        </div>
        <hr />
    }

</div>

EShop.MVC2/Views/Shared/LoginStatus.cshtml
@{ 
    var identity = this.ViewContext.HttpContext.User.Identity;
}

<div style="overflow:hidden;" class = "categories_list">
    @if(Request.IsAuthenticated && identity.IsAuthenticated)
    {
        <div style="float:right"> <b>@identity.Name</b> 
        @Html.ActionLink("Выход", "Logoff", "Account" , new { controller = "Account" }, new { style = "border-bottom: 1px dashed #000080; text-decoration: none;" })</div>
    }
    else
    {
        <div style="float:right"> @Html.ActionLink("Вход", "Login", new { controller = "Account" }, new { style = "border-bottom: 1px dashed #000080; text-decoration: none;" })
        или @Html.ActionLink("Регистрация", "Users", new { controller = "Account" }, new { @class = "categories_list", style = "border-bottom: 1px dashed #000080; text-decoration: none;" })</div>
    }
</div>

EShop.MVC2/Views/Shared/Navigate.cshtml
@using EShop.MVC2.Models

@{
    var Root = ViewData["Root"] as List<CategoryList>; //корневые категории
    var subCat1 = ViewData["Level1"] as List<CategoryList>; //подкатегории 1 - го уровня
    var subCat2 = ViewData["Level2"] as List<CategoryList>; // подкатегории 2-го уровня
    var selected0 = ViewBag.IdLevel0 as int?;//id корневой категории (если надо, то не null)
    var selected1 = ViewBag.IdLevel1 as int?;//id подкатегории 1-го уровня (если надо, то не null)
    var selected2 = ViewBag.IdLevel2 as int?;//id подкатегории 2-го уровня (если надо, то не null)   
}

<ul style="padding: 0; margin: 0;">
    @foreach (var c in Root)
    {
        <li style="text-align: left; list-style-type: none; padding: 0px; margin-left: -5px;" >
            
            @if (selected0 == c.Id  && subCat1 != null)
            {
                if (selected1 == null)
                {
                    <b>@Html.ActionLink(c.Name, "Market", new { controller = "Home", id = c.Id }, new { @class = "categories_list" })</b> @*выделяем жирным шрифтом выбранную корневую категорию*@
                }
                else
                {
                    @Html.ActionLink(c.Name, "Market", new { controller = "Home", id = c.Id }, new { @class = "categories_list" })@*не выделяем жирным шрифтом выбранную корневую категорию т.к. выбрана подкатегория*@
                }
                <ul style="padding: 0; margin: 0;">
                    @foreach (var sc1 in subCat1)
                    {
                        <li style="text-align: left; list-style-type: none; padding: 0; margin-left: 10px;">
                            @if (selected1 != null && sc1.Id == selected1)
                            {
                                if (selected2 == null)
                                {
                                    <b>@Html.ActionLink(sc1.Name, "Market", new { controller = "Home", id = sc1.Id }, new { @class = "categories_list" })</b> @*выделяем жирным шрифтом  выбранную подкатегорию 1-го уровня*@
                                }
                                else
                                {
                                    @Html.ActionLink(sc1.Name, "Market", new { controller = "Home", id = sc1.Id }, new { @class = "categories_list" })  @*не выделяем жирным шрифтом выбранную подкатегорию, т.к. выбрана подкатегория 2-го уровня*@
                                }

                                <ul style="padding: 0; margin: 0;">
                                    @foreach (var sc2 in subCat2)
                                    {
                                        <li style="text-align: left; list-style-type: none; padding: 0; margin-left: 15px;">
                                            @if (selected2 != null && sc2.Id == selected2)
                                            {
                                                <b>@Html.ActionLink(sc2.Name, "Market", new { controller = "Home", id = sc2.Id }, new { @class = "categories_list" })</b>@*выделяем жирным шрифтом выбранную подкатегорию 2-го уровня*@
                                            }
                                            else
                                            {
                                                @Html.ActionLink(sc2.Name, "Market", new { controller = "Home", id = sc2.Id }, new { @class = "categories_list" })
                                            }                                                                                
                                        </li>
                                    }
                                </ul>
                            }
                            else
                            {
                                @Html.ActionLink(sc1.Name, "Market", new { controller = "Home", id = sc1.Id }, new { @class = "categories_list" })
                            }                           
                        </li>
                    }
                </ul>
            }
            else
            {
                @Html.ActionLink(c.Name, "Market", new { controller = "Home", id = c.Id }, new { @class = "categories_list" })
            }
        </li>
    }
</ul>

EShop.MVC2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="~/Content/Images/favicon.ico" /> @*это иконка сайта для отображения в браузере*@
    <script src="~/Scripts/jquery-2.1.4.min.js" type="text/javascript"></script>
</head>

<body>
    
    <table align ="center" width="1280" cellspacing="8" table-layout="fixed">
        <tr>
            <td colspan="3" id="header">
                <div class="logo">
                    <a href="/">
                        <img src="~/Content/Images/BlackLogo.png" alt="no image" />
                    </a>
                </div>
                <img src="~/Content/Images/BlackLogo.png" alt="no image" />
            </td>
        </tr>
        
        <tr>
            <td colspan="3" id="menuPanel">
                <table width="100%" class="title" cellspacing="0" cellpadding="0" border="0" style="border-collapse: collapse; ">
                    <tr>
                        <td width="80%">menu & status line</td>
                        @*<td style="text-align:right">@Html.ActionLink("Вход", "Login", new { controller = "Account" }, new { style = "border-bottom: 1px dashed #000080", @class = "categories_list" })</td>*@
                        <td>@Html.Partial("LoginStatus") </td>
                        @*<td style="text-align:right">@Html.ActionLink("Регистрация", "Users", new { controller = "Account" }, new { style = "border-bottom: 1px dashed #000080", @class = "categories_list" })</td>*@
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td id="leftPanel">

                @Html.Action("Categories", "Home", new {id = ViewBag.Selected})

                @*@RenderSection("LeftSideBar", required: false)*@
            </td>
            <td id ="contentPanel">
                <span>@RenderBody()</span>
                @*@RenderSection("contentLeftPanel", required: true)*@
            </td>
            <td id="rightPanel">
                @{ Html.RenderAction("GetExRates", "Currency"); } @*тут вызывается метод GetExRates контроллера /Controllers/СurrencyController.cs*@
                <hr />
                @{ Html.RenderAction("Index", "Search"); } @*тут вызывается метод Index контроллера /Controllers/SearchController.cs*@
                @*@RenderSection("RightSideBar", required: false)*@

                @Html.Partial("AdminPanel")                
            </td>
        </tr>

        <tr>
            <td colspan="3" style="text-align:center">
                <span class="footer">@DateTime.Now.Year - EShop application</span>
            </td>
        </tr>
    </table>
</body>
</html>