EShop.MVC2/Controllers/CurrencyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EShop.MVC2.Models;
using System.Web.Caching;

namespace EShop.MVC2.Controllers
{
    public class CurrencyController : Controller
    {
        //Метод для получения данных о курсах валют
        //Запрос сюда приходит из мастер-страницы /Views/Shared/_Layout.cshtml
        //(см. @{ Html.RenderAction("GetExRates", "Currency"); })
        //полученные данные отправляются в частичное представление /Views/Currency/GetExRates.cshtml для отрисовки HTML разметки

        // GET: /Currency/
        public ActionResult GetExRates()
        {
            IEnumerable<ExRateItem> items = null;
            var cache = HttpContext.Cache;
            if (cache["exRatesData"] == null)
            {
                var exRateClient = new ExRates.ExRatesSoapClient();
                var exRatesData = exRateClient.ExRatesDaily(DateTime.Now);
                //ViewBag.UpdateDate = DateTime.Now;//время получения курсов от НБРБ
                items = exRatesData.Tables[0].Select(
                            "Cur_Abbreviation = 'RUB' OR Cur_Abbreviation='USD' OR Cur_Abbreviation='EUR'").Select(row => new ExRateItem()
                            {
                                Exchange = row["Cur_Abbreviation"].ToString(),//код валюты: USD, EUR
                                Rate = (decimal)row["Cur_OfficialRate"]//значение курса
                            }).ToArray();

                cache.Insert("exRatesData", items, null, Cache.NoAbsoluteExpiration, TimeSpan.FromMinutes(120), CacheItemPriority.Normal, null);
                cache.Insert("updateTime", DateTime.Now.ToUniversalTime(), null, Cache.NoAbsoluteExpiration, TimeSpan.FromMinutes(120), CacheItemPriority.Normal, null);
            }
            items = cache["exRatesData"] as IEnumerable<ExRateItem>;
            ViewBag.UpdateDate = cache["updateTime"];
            return PartialView("GetExRates", items);
        }
	}
}

EShop.MVC2/Views/Currency/GetExRates.cshtml
@*Здесь отрисовывается таблица с курсами валют.
Данные Model приходят из контроллера /Controllers/CurrencyController.cs
А к этому контроллеру идет обращение из мастер-страницы Views/Shared/_Layout.cshtml
смотри @{ Html.RenderAction("GetExRates", "Currency"); }*@

@model IEnumerable<EShop.MVC2.Models.ExRateItem>

<table>
    <thead style="background-color:snow; font-weight:bold;">
    <tr>
        <td colspan="2">Курсы валют</td>
    </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            DateTime? dt = ViewBag.UpdateDate as DateTime?;
            var dt2 = (dt == null) ? "undefined" : dt.Value.ToLocalTime().ToString();
            foreach (var rate in Model)
            {
                <tr>
                    <td>@rate.Exchange</td>
                    <td>@string.Format("{0:N2}", rate.Rate)</td>
                </tr>
            }
            <tr>
                <td colspan="2" class="small title">
                    Update: @dt2
                </td>
            </tr>
        }
    </tbody>
    
</table>